### ISSUE TITLE
Feican LED Bulb flashing

### ISSUE THREAD

**Issue by pickeld** [corbanmailloux/esp-mqtt-rgb-led#24] opened 2017-07-29 20:10 UTC
hey, i was able to flash your code to the lamp and control it using MQTT, thank you for your hard work!
my Feican lights are RGBW which means i can use the warm white lights too.
in your code then is no such option, do you think its possible to add the ability to control the white lights too?

thank you and have a great week

**Comment by Landrash** [comment] 2017-07-30 11:37
@pickeld se #7 . Duplicate request.

**Comment by corbanmailloux** [comment] 2017-07-31 01:33
Hey @pickeld. I'm going to close this as a duplicate of #7. Please follow the conversation there.

**Closed as completed by corbanmailloux** 2017-07-31 01:33 UTC
Labels: duplicate

**Comment by corbanmailloux** [comment] 2017-08-02 17:22
Hi @pickeld. As you'll see in #7, I've added white channel support for this project. If you get a chance to, please test out the new version with your system and let me know how it's working.

**Comment by pickeld** [comment] 2017-08-11 23:46
you are awesome! working perfectly! thank you :)

**Comment by corbanmailloux** [comment] 2017-08-12 03:06
Good to hear!
